name: qi_dbt_project
version: "1.0"
profile: qi_dbt_project

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"

models:
  qi_dbt_project:
    market:
      +database: market
      +schema: market        # harmless; macro ignores it
      +materialized: table
      weekly_prices:
        +tags: [ 'agg_weekly' ]
      monthly_prices:
        +tags: [ 'agg_monthly' ]
      quarterly_prices:
        +tags: [ 'agg_quarterly' ]
    fundamentals:
      +database: fundamentals
      +schema: fundamentals  # harmless; macro ignores it
      +materialized: table
    meta:
      +database: meta
      +schema: meta
      +materialized: table
    analytics:
      +database: analytics
      +schema: analytics
      +materialized: view