qi_dbt_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      threads: 1
      host: "{{ env_var(\"CLICKHOUSE_HOST\", \"qi-clickhouse\") }}"
      port: "{{ env_var(\"CLICKHOUSE_PORT\", \"8123\") | int }}"
      user: "{{ env_var(\"CLICKHOUSE_USER\", \"qi\") }}"
      password: "{{ env_var(\"CLICKHOUSE_PASSWORD\", \"mysecurepassword\") }}"
      database: "{{ env_var(\"CLICKHOUSE_DB\", \"default\") }}"
      schema: "{{ env_var(\"CLICKHOUSE_DB\", \"default\") }}"
      secure: false
