qi_dbt_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: localhost
      port: 8124
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      database: default